### ISSUE TITLE
Redundant error message( Details of Complaint ) on Edit Item Modal(Investigation Report)

### ISSUE THREAD

**Issue by SunandaMukherjee23** [santanucst/tml-ca#159]
Details of complaint error message  still remains after changing the complaint type.
![details of complaint error message](https://user-images.githubusercontent.com/41181693/44340394-53a85c80-a4a2-11e8-95e2-2e4c5ab48cac.PNG)

**Comment by susmitaseal** [comment]
_fixed.._
